<?php

/**
 * @file
 * Install, update and uninstall functions for the Evidence module.
 */
use Drupal\user\RoleInterface;

/**
 * Implements hook_install().
 */
function evidence_install(): void {
  $permissions_for_authenticated = [
    'create evidence',
    'edit evidence',
    'view evidence',
  ];
  user_role_grant_permissions(RoleInterface::AUTHENTICATED_ID, $permissions_for_authenticated);
}
